# Generated by Django 5.2.14 on 2026-05-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('owner_type', models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('FAMILY', 'Aile'), ('OTHER', 'Diğer')], default='COMPANY', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('INTERNET', 'İnternet'), ('PHONE', 'Telefon'), ('GSM', 'GSM'), ('ELECTRICITY', 'Elektrik'), ('NATURAL_GAS', 'Doğalgaz'), ('WATER', 'Su'), ('SOFTWARE', 'Yazılım'), ('AIDAT', 'Aidat'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('provider_name', models.CharField(blank=True, default='', max_length=128)),
                ('account_no', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('service_no', models.CharField(blank=True, default='', max_length=64)),
                ('phone_no', models.CharField(blank=True, default='', max_length=32)),
                ('location_label', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.TextField(blank=True, default='')),
                ('default_payment_method', models.CharField(default='AUTO', max_length=16)),
                ('package_name', models.CharField(blank=True, default='', max_length=128)),
                ('expected_monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='parties.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL)),
                ('default_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parties.bank')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='parties.institution')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='parties.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('campaign_name', models.CharField(blank=True, default='', max_length=128)),
                ('committed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('normal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cancellation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('APPROACHING', 'Yaklaşıyor'), ('EXPIRED', 'Süresi Doldu'), ('RENEWED', 'Yenilendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16)),
                ('reminder_days', models.JSONField(blank=True, default=list)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_created', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Taahhüt',
                'verbose_name_plural': 'Taahhütler',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriodCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('period_label', models.CharField(blank=True, default='', max_length=32)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('IMPORT_DRAFT', 'Import Draft'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_charges_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_charges', to='finance.payableitem')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_charges', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Abonelik Dönemsel Ücret',
                'verbose_name_plural': 'Abonelik Dönemsel Ücretler',
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'service_type'], name='subscriptio_status_2f0b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionperiodcharge',
            unique_together={('subscription', 'period_label', 'due_date')},
        ),
    ]
