# Generated by Django 6.0.4 on 2026-05-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyasset',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alıcı'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='district',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='independent_section',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Bağımsız Bölüm'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='parties.company', verbose_name='Malik (Şirket)'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='parties.person', verbose_name='Malik (Şahıs)'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='parcel_info',
            field=models.CharField(blank=True, default='', help_text='Örn. 1234/56', max_length=128, verbose_name='Ada/Parsel'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Daire'), ('SHOP', 'İşyeri / Dükkân'), ('OFFICE', 'Ofis'), ('LAND', 'Arsa / Arazi'), ('WAREHOUSE', 'Depo'), ('FACTORY', 'Fabrika'), ('HOTEL', 'Otel'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=16, verbose_name='Mülk Tipi'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='province',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Satış Tarihi'),
        ),
        migrations.AddField(
            model_name='propertyasset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('SOLD', 'Satıldı'), ('RENTED', 'Kirada'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='propertyasset',
            name='owner_type',
            field=models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('MIXED', 'Ortak'), ('OTHER', 'Diğer')], default='PERSON', max_length=16, verbose_name='Sahip Tipi'),
        ),
    ]
