# Generated by Django 5.2.14 on 2026-05-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('DANGER', 'Acil'), ('SUCCESS', 'Başarı')], default='INFO', max_length=16)),
                ('channel', models.CharField(choices=[('SISTEM_ICI', 'Sistem İçi'), ('EMAIL', 'E-posta'), ('TELEGRAM_DRY_RUN', 'Telegram Dry-run'), ('TELEGRAM_TEST', 'Telegram Test'), ('TELEGRAM_GERCEK', 'Telegram Gerçek')], default='SISTEM_ICI', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız'), ('MUTED', 'Susturulmuş'), ('SCHEDULED', 'Zamanlandı')], db_index=True, default='PENDING', max_length=16)),
                ('related_app', models.CharField(blank=True, default='', max_length=64)),
                ('related_model', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
