# Generated by Django 6.0.4 on 2026-05-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('PAYABLE', 'Ödeme'), ('TASK', 'Görev'), ('SUBSCRIPTION', 'Abonelik'), ('SITE_DUES', 'Site Aidatları'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEE', 'Teminat'), ('INTEGRATOR', 'Entegratör/Kontör'), ('REPORT', 'Rapor'), ('SYSTEM', 'Sistem'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='dry_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='real_send_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='related_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='INFO', max_length=12),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='target_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('TELEGRAM', 'Telegram'), ('EMAIL', 'E-posta'), ('SYSTEM', 'Sistem'), ('SISTEM_ICI', 'Sistem İçi'), ('TELEGRAM_DRY_RUN', 'Telegram Dry-run'), ('TELEGRAM_TEST', 'Telegram Test'), ('TELEGRAM_GERCEK', 'Telegram Gerçek')], default='DASHBOARD', max_length=24),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('DRY_RUN', 'Dry-run'), ('TEST', 'Test'), ('READY', 'Hazır'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız'), ('SUPPRESSED', 'Bastırıldı'), ('CANCELLED', 'İptal'), ('MUTED', 'Susturulmuş'), ('SCHEDULED', 'Zamanlandı')], db_index=True, default='DRY_RUN', max_length=16),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAYABLE', 'Ödeme'), ('TASK', 'Görev'), ('SUBSCRIPTION', 'Abonelik'), ('SITE_DUES', 'Site Aidatları'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEE', 'Teminat'), ('INTEGRATOR', 'Entegratör/Kontör'), ('REPORT', 'Rapor'), ('SYSTEM', 'Sistem'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('dashboard_enabled', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
                'ordering': ['user_id', 'category'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('PAYABLE', 'Ödeme'), ('TASK', 'Görev'), ('SUBSCRIPTION', 'Abonelik'), ('SITE_DUES', 'Site Aidatları'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEE', 'Teminat'), ('INTEGRATOR', 'Entegratör/Kontör'), ('REPORT', 'Rapor'), ('SYSTEM', 'Sistem'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('trigger_type', models.CharField(choices=[('DUE_DATE', 'Vade'), ('OVERDUE', 'Gecikmiş'), ('STATUS_CHANGE', 'Durum Değişimi'), ('THRESHOLD', 'Eşik'), ('MANUAL', 'Manuel'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('channel', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('TELEGRAM', 'Telegram'), ('EMAIL', 'E-posta'), ('SYSTEM', 'Sistem'), ('SISTEM_ICI', 'Sistem İçi'), ('TELEGRAM_DRY_RUN', 'Telegram Dry-run'), ('TELEGRAM_TEST', 'Telegram Test'), ('TELEGRAM_GERCEK', 'Telegram Gerçek')], default='DASHBOARD', max_length=24)),
                ('days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dry_run_only', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='INFO', max_length=12)),
                ('title_template', models.CharField(blank=True, default='', max_length=255)),
                ('message_template', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim Kuralı',
                'verbose_name_plural': 'Bildirim Kuralları',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationrule'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['category', 'status'], name='notificatio_categor_39d250_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['dry_run', '-created_at'], name='notificatio_dry_run_b641ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'category')},
        ),
    ]
