# Generated by Django 5.2.14 on 2026-05-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('owner_type', models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('FAMILY', 'Aile'), ('OTHER', 'Diğer')], default='PERSON', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('BAGKUR', 'BAĞKUR'), ('SSK', 'SSK'), ('BES', 'BES'), ('ITO', 'İTO Aidatı'), ('TAX', 'Vergi'), ('MUNICIPAL', 'Belediye'), ('OTHER', 'Diğer Resmi')], db_index=True, max_length=16)),
                ('reference_no', models.CharField(blank=True, default='', help_text='TC, Sicil, Vergi no, vs.', max_length=64)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Aylık'), ('QUARTERLY', '3 Aylık'), ('SEMI_ANNUAL', '6 Aylık'), ('YEARLY', 'Yıllık'), ('INSTALLMENT', 'Taksit'), ('CUSTOM', 'Özel')], default='MONTHLY', max_length=16)),
                ('default_due_day', models.IntegerField(blank=True, null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('default_payment_method', models.CharField(default='EFT', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles', to='parties.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('default_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parties.bank')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles', to='parties.institution')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles', to='parties.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resmi Ödeme Profili',
                'verbose_name_plural': 'Resmi Ödeme Profilleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialPaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('period_label', models.CharField(blank=True, default='', max_length=32)),
                ('installment_no', models.IntegerField(blank=True, help_text='Taksit no (örn. İTO 1/2)', null=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('GENERATED', 'Toplu Üretildi'), ('IMPORT_DRAFT', 'Import Draft'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_periods_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_periods', to='finance.payableitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='official_payments.officialpaymentprofile')),
            ],
            options={
                'verbose_name': 'Resmi Ödeme Dönemi',
                'verbose_name_plural': 'Resmi Ödeme Dönemleri',
                'ordering': ['-due_date'],
                'unique_together': {('profile', 'period_label', 'installment_no', 'due_date')},
            },
        ),
    ]
