# Generated by Django 6.0.4 on 2026-05-13 19:03

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(choices=[('TRIAL', 'Deneme (14 gün)'), ('BASIC', 'Temel'), ('PRO', 'Pro'), ('ENTERPRISE', 'Kurumsal')], default='TRIAL', max_length=16, verbose_name='Abonelik Planı')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='İletişim E-postası')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='Deneme Bitiş')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('primary_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Birincil Sahip')),
            ],
            options={
                'verbose_name': 'Organizasyon / Holding',
                'verbose_name_plural': 'Organizasyonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('sector', models.CharField(choices=[('TEKSTIL', 'Tekstil'), ('ENERJI', 'Enerji'), ('INSAAT', 'İnşaat'), ('GAYRIMENKUL', 'Gayrimenkul'), ('KISISEL', 'Kişisel / Aile'), ('SANAYI', 'Sanayi'), ('HUKUK', 'Hukuk Bürosu'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Sektör')),
                ('active_modules', models.JSONField(blank=True, default=list, help_text="Boş ise SECTOR_DEFAULT_MODULES tablosundan sektör default'u kullanılır", verbose_name='Aktif Modüller')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenancy.organization', verbose_name='Organizasyon')),
            ],
            options={
                'verbose_name': 'Tenant (Sektör)',
                'verbose_name_plural': "Tenant'lar (Sektörler)",
                'ordering': ['organization__name', 'slug'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenantschema')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': "Domain'ler",
            },
        ),
    ]
