# Generated by Django 5.2.14 on 2026-05-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('owner_type', models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('FAMILY', 'Aile'), ('OTHER', 'Diğer')], default='COMPANY', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('RENT', 'Kira'), ('SMMM', 'SMMM'), ('OCCUPATIONAL_SAFETY', 'İş Güvenliği'), ('DOMAIN', 'Domain'), ('HOSTING', 'Hosting'), ('NOTARY', 'Noter'), ('K2', 'K2 Belgesi'), ('SERVICE', 'Hizmet'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=128)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Aylık'), ('QUARTERLY', '3 Aylık'), ('SEMI_ANNUAL', '6 Aylık'), ('YEARLY', 'Yıllık'), ('ONE_TIME', 'Tek Sefer'), ('CUSTOM', 'Özel')], default='MONTHLY', max_length=16)),
                ('default_due_day', models.IntegerField(blank=True, help_text="Ayın N'i (1-31)", null=True)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('default_payment_method', models.CharField(default='EFT', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='parties.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('default_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parties.bank')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='parties.institution')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles', to='parties.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Düzenli Ödeme Profili',
                'verbose_name_plural': 'Düzenli Ödeme Profilleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegularPaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('period_label', models.CharField(blank=True, default='', max_length=32)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('GENERATED', 'Toplu Üretildi'), ('IMPORT_DRAFT', 'Import Draft'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_periods_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_periods', to='finance.payableitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='regular_payments.regularpaymentprofile')),
            ],
            options={
                'verbose_name': 'Düzenli Ödeme Dönemi',
                'verbose_name_plural': 'Düzenli Ödeme Dönemleri',
                'ordering': ['-due_date'],
                'unique_together': {('profile', 'period_label', 'due_date')},
            },
        ),
    ]
