# Generated by Django 5.2.14 on 2026-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(blank=True, default='', verbose_name='Değer')),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=16, verbose_name='Tip')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'ordering': ['key'],
            },
        ),
    ]
