# Generated by Django 5.2.14 on 2026-05-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Oluştur'), ('UPDATE', 'Güncelle'), ('ARCHIVE', 'Pasifleştir'), ('RESTORE', 'Geri Al'), ('HARD_DELETE', 'Kalıcı Sil'), ('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış'), ('SEED', 'Tohumlama'), ('PERMISSION_CHANGE', 'Yetki Değişikliği'), ('VIEW', 'Görüntüleme')], db_index=True, max_length=32)),
                ('app_label', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Aktör')),
            ],
            options={
                'verbose_name': 'Audit Kaydı',
                'verbose_name_plural': 'Audit Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_audit_app_lab_ecff98_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
