# Generated by Django 6.0.4 on 2026-05-07 08:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruvaUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('code', models.CharField(db_index=True, help_text='Örn. A4.17, B2.28', max_length=32, unique=True, verbose_name='Daire Kodu')),
                ('block', models.CharField(blank=True, default='', max_length=16, verbose_name='Blok')),
                ('unit_no', models.CharField(blank=True, default='', max_length=16, verbose_name='Daire No')),
                ('owner_type', models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('FAMILY', 'Aile'), ('OTHER', 'Diğer')], default='PERSON', max_length=16, verbose_name='Sahip Tipi')),
                ('usage_type', models.CharField(choices=[('OWNER_OCCUPIED', 'Malik Oturuyor'), ('RENTED', 'Kirada'), ('EMPTY', 'Boş'), ('OTHER', 'Diğer')], default='OWNER_OCCUPIED', max_length=24, verbose_name='Kullanım')),
                ('default_due_day', models.IntegerField(default=20, help_text="SiteX için ayın 20'si (override edilebilir).", verbose_name='Varsayılan Son Ödeme Günü')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('SOLD', 'Satıldı'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Alıcı')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_units_created', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_units', to='parties.company', verbose_name='Malik (Şirket)')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_units', to='parties.person', verbose_name='Malik (Şahıs)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_units_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SiteX Daire',
                'verbose_name_plural': 'SiteX Daireleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PruvaStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('period_label', models.CharField(blank=True, default='', help_text='Anayasa 3.16 long-format yyyy-mm.', max_length=16, verbose_name='Dönem (yyyy-mm)')),
                ('due_date', models.DateField(verbose_name='Son Ödeme')),
                ('aidat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Aidat')),
                ('gider_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Gider Katılımı')),
                ('previous_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Önceki Bakiye')),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Gecikme')),
                ('other', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Diğer')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Toplam')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16, verbose_name='Durum')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('IMPORT_DRAFT', 'Import Draft'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16, verbose_name='Kaynak')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_statements_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_statement', to='finance.payableitem', verbose_name='Bağlı PayableItem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_statements_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='pruva.pruvaunit', verbose_name='Daire')),
            ],
            options={
                'verbose_name': 'SiteX Ekstresi',
                'verbose_name_plural': 'SiteX Ekstreleri',
                'ordering': ['-year', '-month', 'unit__code'],
            },
        ),
        migrations.CreateModel(
            name='PruvaSiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('document_type', models.CharField(choices=[('BUDGET', 'Yıllık Bütçe'), ('AUDIT_REPORT', 'Denetim Raporu'), ('GENERAL_ASSEMBLY', 'Genel Kurul'), ('TITLE_DEED', 'Tapu / Resmi Belge'), ('MANAGEMENT_NOTICE', 'Yönetim Duyurusu'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24, verbose_name='Belge Tipi')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yıl')),
                ('period_label', models.CharField(blank=True, default='', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruva_site_docs', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_site_docs_uploaded', to=settings.AUTH_USER_MODEL)),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_documents', to='pruva.pruvaunit', verbose_name='İlgili Daire (varsa)')),
            ],
            options={
                'verbose_name': 'SiteX Site Belgesi',
                'verbose_name_plural': 'SiteX Site Belgeleri',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PruvaAidatDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('period_label', models.CharField(blank=True, default='', max_length=16)),
                ('date', models.DateField(verbose_name='Tarih')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('direction', models.CharField(choices=[('PAID_TO_PERSON', 'Şahsa Ödendi'), ('RECEIVED_FROM_PERSON', 'Şahıstan Tahsil Edildi'), ('OFFSET', 'Mahsuplaşma'), ('OTHER', 'Diğer')], default='PAID_TO_PERSON', max_length=24, verbose_name='Yön')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('OPEN', 'Açık'), ('SETTLED', 'Kapandı'), ('CANCELLED', 'İptal')], db_index=True, default='OPEN', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_aidat_differences', to='parties.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_aidat_diffs_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_aidat_differences', to='documents.document')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_aidat_differences', to='parties.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_aidat_diffs_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aidat_differences', to='pruva.pruvaunit')),
            ],
            options={
                'verbose_name': 'SiteX Aidat Farkı',
                'verbose_name_plural': 'SiteX Aidat Farkları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PruvaStatementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('document_role', models.CharField(choices=[('STATEMENT', 'Aylık Ekstre'), ('RECEIPT', 'Dekont'), ('BUDGET', 'Bütçe'), ('REPORT', 'Rapor'), ('TITLE_DEED', 'Tapu / Belge'), ('OTHER', 'Diğer')], default='STATEMENT', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruva_statement_links', to='documents.document')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pruva.pruvastatement')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruva_statement_docs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SiteX Ekstre Belgesi',
                'verbose_name_plural': 'SiteX Ekstre Belgeleri',
                'ordering': ['-created_at'],
                'unique_together': {('statement', 'document', 'document_role')},
            },
        ),
        migrations.AddIndex(
            model_name='pruvastatement',
            index=models.Index(fields=['year', 'month'], name='pruva_pruva_year_b87c82_idx'),
        ),
        migrations.AddIndex(
            model_name='pruvastatement',
            index=models.Index(fields=['status', 'due_date'], name='pruva_pruva_status_da7afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pruvastatement',
            unique_together={('unit', 'year', 'month')},
        ),
    ]
