# Generated by Django 6.0.4 on 2026-05-07 08:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        ('parties', '0002_propertyasset_buyer_name_propertyasset_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('name', models.CharField(max_length=128, verbose_name='Belediye Adı')),
                ('province', models.CharField(blank=True, default='', max_length=64, verbose_name='İl')),
                ('district', models.CharField(blank=True, default='', max_length=64, verbose_name='İlçe')),
                ('website', models.URLField(blank=True, default='', verbose_name='Web Sitesi')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
            ],
            options={
                'verbose_name': 'Belediye',
                'verbose_name_plural': 'Belediyeler',
                'ordering': ['name'],
                'unique_together': {('name', 'province', 'district')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('tax_year', models.IntegerField(verbose_name='Yıl')),
                ('total_accrual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Tahakkuk Toplam')),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Ödenen')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kalan')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('PARTIAL_PAID', 'Kısmi Ödendi'), ('PAID', 'Ödendi'), ('OVERDUE', 'Geciken'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16, verbose_name='Durum')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('IMPORT_DRAFT', 'Import Draft'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16, verbose_name='Kaynak')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_tax_years_created', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_years', to='properties.municipality', verbose_name='Belediye')),
                ('property_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_years', to='parties.propertyasset', verbose_name='Mülk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_tax_years_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emlak Vergisi Yılı',
                'verbose_name_plural': 'Emlak Vergisi Yılları',
                'ordering': ['-tax_year', 'property_asset__name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTaxInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('installment_no', models.IntegerField(help_text='1 = Mayıs, 2 = Kasım, 0 = Tek/Diğer', verbose_name='Taksit No')),
                ('due_date', models.DateField(verbose_name='Son Ödeme')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('OVERDUE', 'Geciken'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16, verbose_name='Durum')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_installments_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_installment', to='finance.payableitem', verbose_name='Bağlı PayableItem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_installments_updated', to=settings.AUTH_USER_MODEL)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='properties.propertytaxyear', verbose_name='Yıl')),
            ],
            options={
                'verbose_name': 'Emlak Vergisi Taksiti',
                'verbose_name_plural': 'Emlak Vergisi Taksitleri',
                'ordering': ['-tax_year__tax_year', 'installment_no'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('document_role', models.CharField(choices=[('DEBT_STATEMENT', 'Borç Dökümü'), ('RECEIPT', 'Makbuz'), ('PAYMENT_PROOF', 'Ödeme Dekontu'), ('MUNICIPAL_NOTICE', 'Belediye Yazısı'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_tax_links', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_tax_docs_uploaded', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.propertytaxinstallment')),
                ('tax_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.propertytaxyear')),
            ],
            options={
                'verbose_name': 'Emlak Vergisi Belgesi',
                'verbose_name_plural': 'Emlak Vergisi Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertytaxyear',
            index=models.Index(fields=['tax_year'], name='properties__tax_yea_f681e1_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytaxyear',
            index=models.Index(fields=['status'], name='properties__status_7d3ea5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertytaxyear',
            unique_together={('property_asset', 'tax_year')},
        ),
        migrations.AlterUniqueTogether(
            name='propertytaxinstallment',
            unique_together={('tax_year', 'installment_no')},
        ),
        migrations.AlterUniqueTogether(
            name='propertytaxdocument',
            unique_together={('tax_year', 'installment', 'document', 'document_role')},
        ),
    ]
