# Generated by Django 6.0.4 on 2026-05-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        ('parties', '0002_propertyasset_buyer_name_propertyasset_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('package_name', models.CharField(max_length=255, verbose_name='Paket Adı')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Alış Tarihi')),
                ('total_credits', models.PositiveIntegerField(default=0, verbose_name='Toplam Kontör')),
                ('remaining_credits', models.PositiveIntegerField(default=0, verbose_name='Kalan Kontör')),
                ('critical_threshold', models.PositiveIntegerField(default=100, verbose_name='Kritik Eşik')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('CRITICAL', 'Kritik'), ('EXHAUSTED', 'Tükendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_credits_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_credit_package', to='finance.payableitem', verbose_name='Bağlı PayableItem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_credits_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontör Paketi',
                'verbose_name_plural': 'Kontör Paketleri',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('provider_name', models.CharField(max_length=128, verbose_name='Sağlayıcı Adı')),
                ('provider_type', models.CharField(choices=[('ETA', 'ETA'), ('PAPINET', 'Papinet'), ('EDM', 'EDM'), ('DIGITAL_PLANET', 'Digital Planet'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24, verbose_name='Sağlayıcı Tipi')),
                ('service_type', models.CharField(choices=[('ACCOUNTING_SOFTWARE', 'Muhasebe Yazılımı'), ('E_INVOICE', 'e-Fatura'), ('E_ARCHIVE', 'e-Arşiv'), ('E_WAYBILL', 'e-İrsaliye'), ('E_LEDGER', 'e-Defter'), ('DEFTER_SAKLAMA', 'Defter Saklama'), ('CREDIT_PACKAGE', 'Kontör Paketi'), ('VERSION_RENEWAL', 'Versiyon Yenileme'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24, verbose_name='Hizmet Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('customer_no', models.CharField(blank=True, default='', max_length=64, verbose_name='Müşteri No')),
                ('account_no', models.CharField(blank=True, default='', max_length=64, verbose_name='Hesap No')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif'), ('CANCELLED', 'İptal'), ('RENEWED', 'Yenilendi'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_services_created', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_services', to='parties.company', verbose_name='Şirket')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_services', to='parties.person', verbose_name='Şahıs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazılım/Entegratör Hizmeti',
                'verbose_name_plural': 'Yazılım/Entegratör Hizmetleri',
                'ordering': ['provider_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('contract_type', models.CharField(choices=[('ANNUAL', 'Yıllık'), ('MONTHLY', 'Aylık'), ('ONE_TIME', 'Tek Seferlik'), ('VERSION_RENEWAL', 'Versiyon Yenileme'), ('DEFTER_SAKLAMA', 'Defter Saklama'), ('TARIFF', 'Tarife'), ('OTHER', 'Diğer')], default='ANNUAL', max_length=24, verbose_name='Sözleşme Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Bitiş')),
                ('renewal_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Yenileme')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('APPROACHING', 'Yaklaşan Bitiş'), ('EXPIRED', 'Süresi Doldu'), ('RENEWED', 'Yenilendi'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_contracts_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_contract', to='finance.payableitem', verbose_name='Bağlı PayableItem')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_to_set', to='integrators.servicecontract', verbose_name='Eski Sözleşme')),
                ('renewed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from_set', to='integrators.servicecontract', verbose_name='Yeni Sözleşme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_contracts_updated', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='integrators.softwareservice', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Hizmet Sözleşmesi',
                'verbose_name_plural': 'Hizmet Sözleşmeleri',
                'ordering': ['-renewal_date', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='IntegratorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('document_role', models.CharField(choices=[('CONTRACT', 'Sözleşme'), ('TARIFF', 'Tarife'), ('INVOICE', 'Fatura'), ('RECEIPT', 'Dekont'), ('CREDIT_PURCHASE', 'Kontör Satın Alma'), ('RENEWAL_DOCUMENT', 'Yenileme Belgesi'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('credit_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='integrators.creditpackage')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrator_links', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrator_docs_uploaded', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='integrators.servicecontract')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='integrators.softwareservice')),
            ],
            options={
                'verbose_name': 'Entegratör Belgesi',
                'verbose_name_plural': 'Entegratör Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_packages', to='integrators.softwareservice', verbose_name='Hizmet'),
        ),
        migrations.AddIndex(
            model_name='softwareservice',
            index=models.Index(fields=['status'], name='integrators_status_706c53_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareservice',
            index=models.Index(fields=['provider_type', 'service_type'], name='integrators_provide_56dcad_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['status'], name='integrators_status_6b0f05_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['end_date'], name='integrators_end_dat_38ab8c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['renewal_date'], name='integrators_renewal_ba54a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integratordocument',
            unique_together={('service', 'contract', 'credit_package', 'document', 'document_role')},
        ),
        migrations.AddIndex(
            model_name='creditpackage',
            index=models.Index(fields=['status'], name='integrators_status_6d2b5c_idx'),
        ),
    ]
