# Generated by Django 6.0.4 on 2026-05-07 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrate_legacy_thread_types(apps, schema_editor):
    """Faz 11: BIREBIR/GRUP/KAYIT_BAGLI → DIRECT/GROUP/RECORD."""
    ChatThread = apps.get_model("chat", "ChatThread")
    ChatThread.objects.filter(thread_type="BIREBIR").update(thread_type="DIRECT")
    ChatThread.objects.filter(thread_type="GRUP").update(thread_type="GROUP")
    ChatThread.objects.filter(thread_type="KAYIT_BAGLI").update(thread_type="RECORD")


def _revert_legacy_thread_types(apps, schema_editor):
    ChatThread = apps.get_model("chat", "ChatThread")
    ChatThread.objects.filter(thread_type="DIRECT").update(thread_type="BIREBIR")
    ChatThread.objects.filter(thread_type="GROUP").update(thread_type="GRUP")
    ChatThread.objects.filter(thread_type="RECORD").update(thread_type="KAYIT_BAGLI")


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_migrate_legacy_thread_types, _revert_legacy_thread_types),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Chat Eki',
                'verbose_name_plural': 'Chat Ekleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('THREAD_CREATED', 'Konu Açıldı'), ('PARTICIPANT_ADDED', 'Katılımcı Eklendi'), ('PARTICIPANT_REMOVED', 'Katılımcı Çıkarıldı'), ('MESSAGE_SENT', 'Mesaj Gönderildi'), ('MESSAGE_DELETED', 'Mesaj Silindi'), ('ATTACHMENT_ADDED', 'Ek Yüklendi'), ('THREAD_ARCHIVED', 'Konu Arşivlendi'), ('THREAD_CLOSED', 'Konu Kapatıldı'), ('READ', 'Okundu')], max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chat Olayı',
                'verbose_name_plural': 'Chat Olayları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('role', models.CharField(choices=[('OWNER', 'Sahip'), ('MEMBER', 'Üye'), ('VIEWER', 'Görüntüleyici')], default='MEMBER', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('muted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chat Katılımcı',
                'verbose_name_plural': 'Chat Katılımcılar',
                'ordering': ['thread_id', 'joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['sent_at'], 'verbose_name': 'Chat Mesaj', 'verbose_name_plural': 'Chat Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['-last_message_at', '-updated_at'], 'verbose_name': 'Chat Thread', 'verbose_name_plural': 'Chat Threads'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Metin'), ('SYSTEM', 'Sistem'), ('FILE', 'Dosya'), ('EVENT', 'Olay')], default='TEXT', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Gönderildi'), ('EDITED', 'Düzenlendi'), ('DELETED', 'Silindi')], default='SENT', max_length=16),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_message_preview',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='related_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('ARCHIVED', 'Arşiv'), ('CLOSED', 'Kapalı')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='related_app',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='related_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='related_object_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(choices=[('DIRECT', 'Birebir'), ('GROUP', 'Grup'), ('RECORD', 'Kayıt Bağlantılı'), ('TASK', 'Görev Bağlantılı'), ('SYSTEM', 'Sistem')], default='DIRECT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'sent_at'], name='chat_chatme_thread__d53411_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'status'], name='chat_chatme_thread__373e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['related_app', 'related_model', 'related_object_id'], name='chat_chatth_related_21e5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['thread_type', 'status'], name='chat_chatth_thread__cac309_idx'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatattachment',
            constraint=models.UniqueConstraint(fields=('message', 'document'), name='uniq_chat_attachment_per_message'),
        ),
        migrations.AddIndex(
            model_name='chatevent',
            index=models.Index(fields=['thread', 'created_at'], name='chat_chatev_thread__371ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatevent',
            index=models.Index(fields=['event_type'], name='chat_chatev_event_t_ac2fde_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='uniq_chat_participant'),
        ),
    ]
