# Generated by Django 5.2.14 on 2026-05-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('NORMAL', 'Normal'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='NORMAL', max_length=8)),
                ('status', models.CharField(choices=[('NEW', 'Yeni'), ('IN_PROGRESS', 'Başladı'), ('WAITING', 'Bekliyor'), ('DEFERRED', 'Ertelendi'), ('DONE', 'Tamamlandı'), ('CANCELLED', 'İptal')], db_index=True, default='NEW', max_length=16)),
                ('related_app', models.CharField(blank=True, default='', max_length=64)),
                ('related_model', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status', 'due_date'], name='tasks_task_assigne_b83e04_idx')],
            },
        ),
    ]
