# Generated by Django 6.0.4 on 2026-05-07 13:40
# Faz 10 — Task model enrichment + TaskComment / TaskAttachment / TaskEvent.
# Eski enum değerleri (NEW/DEFERRED/DONE/URGENT) yeni semantiğe veri kaybetmeden taşınır.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrate_legacy_task_values(apps, schema_editor):
    """NEW→OPEN, DEFERRED→POSTPONED, DONE→COMPLETED, URGENT→CRITICAL."""
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="NEW").update(status="OPEN")
    Task.objects.filter(status="DEFERRED").update(status="POSTPONED")
    Task.objects.filter(status="DONE").update(status="COMPLETED")
    Task.objects.filter(priority="URGENT").update(priority="CRITICAL")


def _revert_legacy_task_values(apps, schema_editor):
    """Geri alma — yeni enum değerlerini eski'ye çevir."""
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="OPEN").update(status="NEW")
    Task.objects.filter(status="POSTPONED").update(status="DEFERRED")
    Task.objects.filter(status="COMPLETED").update(status="DONE")
    Task.objects.filter(priority="CRITICAL").update(priority="URGENT")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_migrate_legacy_task_values, _revert_legacy_task_values),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Görev Belgesi',
                'verbose_name_plural': 'Görev Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('body', models.TextField(verbose_name='Metin')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sistem')),
            ],
            options={
                'verbose_name': 'Görev Yorumu',
                'verbose_name_plural': 'Görev Yorumları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Oluşturuldu'), ('UPDATED', 'Güncellendi'), ('ASSIGNED', 'Atandı'), ('STATUS_CHANGED', 'Durum Değişti'), ('POSTPONED', 'Ertelendi'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal'), ('REOPENED', 'Yeniden Açıldı'), ('COMMENTED', 'Yorum'), ('ATTACHMENT_ADDED', 'Belge Eklendi')], db_index=True, max_length=24)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Görev Olayı',
                'verbose_name_plural': 'Görev Olayları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal'),
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='İptal Eden'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlandı'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Son Saat'),
        ),
        migrations.AddField(
            model_name='task',
            name='postponed_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ertelendi → Tarih'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('SYSTEM', 'Sistem'), ('IMPORT', 'Import'), ('OTHER', 'Diğer')], default='MANUAL', max_length=12, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Atanan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Tarih'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Düşük'), ('NORMAL', 'Normal'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='NORMAL', max_length=12, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_app',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_object_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Açık'), ('IN_PROGRESS', 'Devam Ediyor'), ('WAITING', 'Bekliyor'), ('POSTPONED', 'Ertelendi'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], db_index=True, default='OPEN', max_length=16, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='tasks_task_status_0eabcf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['related_app', 'related_model', 'related_object_id'], name='tasks_task_related_334ed8_idx'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='taskattachment',
            constraint=models.UniqueConstraint(fields=('task', 'document'), name='uniq_task_document'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', '-created_at'], name='tasks_taske_task_id_607d8a_idx'),
        ),
    ]
