# Generated by Django 5.2.14 on 2026-05-05 20:57

import apps.documents.models
import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Ad')),
                ('stored_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Sistem Adı')),
                ('file', models.FileField(max_length=512, storage=apps.documents.storage.PrivateStorage(), upload_to=apps.documents.models._document_upload_path)),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256')),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('extension', models.CharField(blank=True, default='', max_length=16)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Fatura'), ('RECEIPT', 'Dekont / Makbuz'), ('CONTRACT', 'Sözleşme'), ('STATEMENT', 'Ekstre'), ('TAX_RECEIPT', 'Vergi Makbuzu'), ('GUARANTEE_LETTER', 'Teminat Mektubu'), ('IMPORT_SOURCE', 'Import Kaynağı'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=24)),
                ('source', models.CharField(choices=[('UPLOAD', 'Manuel Yükleme'), ('IMPORT', 'Import Çıktısı'), ('SYSTEM', 'Sistem Üretimi')], default='UPLOAD', max_length=16)),
                ('related_app', models.CharField(blank=True, default='', max_length=64)),
                ('related_model', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['document_type', '-uploaded_at'], name='documents_d_documen_b91311_idx'), models.Index(fields=['related_app', 'related_model', 'related_object_id'], name='documents_d_related_4262d6_idx')],
            },
        ),
    ]
