# Generated by Django 6.0.4 on 2026-05-07 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('report_type', models.CharField(choices=[('PAYABLES', 'Geciken/Yaklaşan Ödemeler'), ('PAYMENTS', 'Ödemeler'), ('SUBSCRIPTIONS', 'Abonelikler'), ('REGULAR_PAYMENTS', 'Düzenli Ödemeler'), ('OFFICIAL_PAYMENTS', 'Resmi Ödemeler'), ('SITE_DUES', 'Site Aidatları'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEES', 'Teminat Komisyonları'), ('INTEGRATORS', 'Entegratör & Kontör'), ('TASKS', 'Görevler'), ('DOCUMENTS', 'Belgeler'), ('AUDIT', 'AuditLog'), ('COMBINED', 'Birleşik')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('default_format', models.CharField(choices=[('XLSX', 'XLSX'), ('CSV', 'CSV')], default='XLSX', max_length=8)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('report_type', models.CharField(choices=[('PAYABLES', 'Geciken/Yaklaşan Ödemeler'), ('PAYMENTS', 'Ödemeler'), ('SUBSCRIPTIONS', 'Abonelikler'), ('REGULAR_PAYMENTS', 'Düzenli Ödemeler'), ('OFFICIAL_PAYMENTS', 'Resmi Ödemeler'), ('SITE_DUES', 'Site Aidatları'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEES', 'Teminat Komisyonları'), ('INTEGRATORS', 'Entegratör & Kontör'), ('TASKS', 'Görevler'), ('DOCUMENTS', 'Belgeler'), ('AUDIT', 'AuditLog'), ('COMBINED', 'Birleşik')], max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('format', models.CharField(choices=[('XLSX', 'XLSX'), ('CSV', 'CSV')], default='XLSX', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RUNNING', 'Çalışıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hatalı'), ('CANCELLED', 'İptal')], default='PENDING', max_length=12)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Rapor Çalıştırma',
                'verbose_name_plural': 'Rapor Çalıştırmaları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__6fc107_idx'), models.Index(fields=['created_by', '-created_at'], name='reports_rep_created_0fc0a2_idx')],
            },
        ),
    ]
