# Generated by Django 6.0.4 on 2026-05-07 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        ('parties', '0002_propertyasset_buyer_name_propertyasset_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeCommissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('period_label', models.CharField(help_text='Örn. 2025-Q2 veya 2025-04', max_length=32, verbose_name='Dönem Etiketi')),
                ('due_date', models.DateField(verbose_name='Son Ödeme')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Komisyon Tutarı')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('LINKED', 'PayableItem Bağlı'), ('PAID', 'Ödendi'), ('OVERDUE', 'Geciken'), ('CANCELLED', 'İptal'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='PENDING', max_length=16, verbose_name='Durum')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('GENERATED', 'Üretildi'), ('IMPORT_DRAFT', 'Import Draft'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16, verbose_name='Kaynak')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_periods_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_commission', to='finance.payableitem', verbose_name='Bağlı PayableItem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_periods_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komisyon Dönemi',
                'verbose_name_plural': 'Komisyon Dönemleri',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('letter_no', models.CharField(db_index=True, max_length=64, verbose_name='Mektup No')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('guarantee_type', models.CharField(choices=[('PHYSICAL', 'Fiziki'), ('ELECTRONIC', 'Elektronik'), ('OTHER', 'Diğer')], default='PHYSICAL', max_length=16, verbose_name='Tip')),
                ('purpose', models.CharField(blank=True, default='', max_length=255, verbose_name='Amaç')),
                ('facility_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Limit/Facility')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Düzenlenme')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Vade')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Komisyon Oranı (%)')),
                ('commission_period', models.CharField(choices=[('MONTHLY', 'Aylık'), ('QUARTERLY', '3 Aylık'), ('SEMI_ANNUAL', '6 Aylık'), ('YEARLY', 'Yıllık'), ('ONE_TIME', 'Tek Seferlik'), ('CUSTOM', 'Özel')], default='QUARTERLY', max_length=16, verbose_name='Komisyon Periyodu')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('APPROACHING', 'Yaklaşan Vade'), ('EXPIRED', 'Süresi Doldu'), ('RETURNED', 'İade'), ('RENEWED', 'Yenilendi'), ('CANCELLED', 'İptal'), ('PASSIVE', 'Pasif'), ('NEEDS_REVIEW', 'Kontrol Gerekli')], db_index=True, default='ACTIVE', max_length=16, verbose_name='Durum')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='İade Tarihi')),
                ('cancelled_at', models.DateField(blank=True, null=True, verbose_name='İptal Tarihi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_letters', to='parties.bank', verbose_name='Banka')),
                ('beneficiary_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_letters', to='parties.institution', verbose_name='Lehdar Kurum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees_created', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_letters', to='parties.company', verbose_name='Şirket')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_letters', to='parties.person', verbose_name='Şahıs')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_to_set', to='guarantees.guaranteeletter', verbose_name='Eski Mektup')),
                ('renewed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from_set', to='guarantees.guaranteeletter', verbose_name='Yeni Mektup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teminat Mektubu',
                'verbose_name_plural': 'Teminat Mektupları',
                'ordering': ['-issue_date', 'letter_no'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('document_role', models.CharField(choices=[('GUARANTEE_LETTER', 'Teminat Mektubu'), ('COMMISSION_RECEIPT', 'Komisyon Dekontu'), ('RETURN_LETTER', 'İade Yazısı'), ('RENEWAL_DOCUMENT', 'Yenileme Belgesi'), ('BANK_NOTICE', 'Banka Yazısı'), ('OTHER', 'Diğer')], default='OTHER', max_length=24)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('commission_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guarantees.guaranteecommissionperiod')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantee_links', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_docs_uploaded', to=settings.AUTH_USER_MODEL)),
                ('guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guarantees.guaranteeletter')),
            ],
            options={
                'verbose_name': 'Teminat Belgesi',
                'verbose_name_plural': 'Teminat Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guaranteecommissionperiod',
            name='guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='guarantees.guaranteeletter', verbose_name='Teminat'),
        ),
        migrations.AddIndex(
            model_name='guaranteeletter',
            index=models.Index(fields=['status'], name='guarantees__status_14c29f_idx'),
        ),
        migrations.AddIndex(
            model_name='guaranteeletter',
            index=models.Index(fields=['expiry_date'], name='guarantees__expiry__60c7b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='guaranteeletter',
            constraint=models.UniqueConstraint(condition=models.Q(('letter_no__gt', '')), fields=('bank', 'letter_no'), name='uniq_bank_letterno_when_set'),
        ),
        migrations.AlterUniqueTogether(
            name='guaranteedocument',
            unique_together={('guarantee', 'commission_period', 'document', 'document_role')},
        ),
        migrations.AddIndex(
            model_name='guaranteecommissionperiod',
            index=models.Index(fields=['due_date'], name='guarantees__due_dat_d831f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guaranteecommissionperiod',
            unique_together={('guarantee', 'period_label')},
        ),
    ]
