# Generated by Django 5.2.14 on 2026-05-05 21:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('owner_type', models.CharField(choices=[('COMPANY', 'Şirket'), ('PERSON', 'Şahıs'), ('FAMILY', 'Aile'), ('OTHER', 'Diğer')], default='COMPANY', max_length=16, verbose_name='Sahip Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='Kategori')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tedarikçi')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Fatura No')),
                ('subscription_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='Abonelik / Hesap No')),
                ('period_label', models.CharField(blank=True, default='', max_length=32, verbose_name='Dönem (örn. 2026-05)')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Fatura Tarihi')),
                ('due_date', models.DateField(verbose_name='Son Ödeme')),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Ödenen')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Bekliyor'), ('APPROACHING', 'Yaklaşıyor'), ('OVERDUE', 'Geciken'), ('PARTIAL_PAID', 'Kısmi Ödendi'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal'), ('ARCHIVED', 'Arşiv'), ('NEEDS_REVIEW', 'Kontrol Gerekli'), ('WAITING_APPROVAL', 'Onay Bekliyor')], db_index=True, default='PENDING', max_length=24, verbose_name='Durum')),
                ('payment_method', models.CharField(choices=[('AUTO', 'Otomatik Talimat'), ('EFT', 'EFT'), ('HAVALE', 'Havale'), ('CREDIT_CARD', 'Kredi Kartı'), ('CASH', 'Nakit'), ('ELDEN', 'Elden'), ('OTHER', 'Diğer')], default='EFT', max_length=16, verbose_name='Ödeme Yöntemi')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('IMPORT_DRAFT', 'Import Draft'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('OTHER', 'Diğer')], default='MANUAL', max_length=16, verbose_name='Kaynak')),
                ('requires_receipt', models.BooleanField(default=False, verbose_name='Dekont Zorunlu')),
                ('requires_double_approval', models.BooleanField(default=False, verbose_name='Çift Onay Zorunlu')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables_approved', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='parties.bank', verbose_name='Banka')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='parties.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='parties.institution', verbose_name='Kurum')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='parties.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura / Ödeme Kalemi',
                'verbose_name_plural': 'Fatura / Ödeme Kalemleri',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('document_role', models.CharField(choices=[('INVOICE', 'Fatura'), ('RECEIPT', 'Dekont'), ('CONTRACT', 'Sözleşme'), ('STATEMENT', 'Ekstre'), ('OTHER', 'Diğer')], default='INVOICE', max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_links', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.payableitem')),
            ],
            options={
                'verbose_name': 'Fatura / Ödeme Belgesi',
                'verbose_name_plural': 'Fatura / Ödeme Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('payment_date', models.DateField(verbose_name='Ödeme Tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('payment_method', models.CharField(choices=[('AUTO', 'Otomatik Talimat'), ('EFT', 'EFT'), ('HAVALE', 'Havale'), ('CREDIT_CARD', 'Kredi Kartı'), ('CASH', 'Nakit'), ('ELDEN', 'Elden'), ('OTHER', 'Diğer')], default='EFT', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING_APPROVAL', 'Onay Bekliyor'), ('APPROVED', 'Onaylı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], db_index=True, default='APPROVED', max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parties.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.payableitem')),
                ('receipt_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Ödeme Hareketi',
                'verbose_name_plural': 'Ödeme Hareketleri',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payableitem',
            index=models.Index(fields=['status', 'due_date'], name='finance_pay_status_2a7010_idx'),
        ),
        migrations.AddIndex(
            model_name='payableitem',
            index=models.Index(fields=['owner_type', 'company', 'person'], name='finance_pay_owner_t_91b92e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payabledocument',
            unique_together={('payable', 'document', 'document_role')},
        ),
    ]
