# Generated by Django 5.2.14 on 2026-05-05 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('RAR', 'RAR'), ('ZIP', 'ZIP'), ('FOLDER', 'Klasör'), ('MANUAL', 'Manuel')], default='EXCEL', max_length=16)),
                ('target_module', models.CharField(choices=[('INVOICE', 'Fatura / Ödeme'), ('SUBSCRIPTION', 'Abonelik'), ('SITEX', 'SiteX'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEE', 'Teminat'), ('OFFICIAL', 'Resmi Ödemeler'), ('INTEGRATOR', 'Entegratör'), ('MASTER', 'Master Tablolar'), ('GENERIC', 'Genel / Tanımsız')], default='GENERIC', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PARSED', 'Parse Edildi'), ('NEEDS_REVIEW', 'Kontrol Bekliyor'), ('APPROVED', 'Onaylandı'), ('COMMITTED', 'Kayıt Edildi'), ('FAILED', 'Hatalı'), ('CANCELLED', 'İptal')], db_index=True, default='DRAFT', max_length=16)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_until', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('ok_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('manual_review_count', models.IntegerField(default=0)),
                ('historical_data', models.BooleanField(default=False, help_text='Geçmiş yıl import (D-018): otomatik görev/bildirim üretmez.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_approved', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': "Import Batch'ler",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDraftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('source_row_number', models.IntegerField()),
                ('record_key', models.CharField(blank=True, db_index=True, default='', help_text='Idempotency için doğal anahtar', max_length=255)),
                ('target_model', models.CharField(blank=True, default='', max_length=64)),
                ('suggested_action', models.CharField(choices=[('CREATE', 'Yeni Oluştur'), ('UPDATE', 'Güncelle'), ('SKIP', 'Atla'), ('MANUAL_REVIEW', 'Manuel İncele')], default='MANUAL_REVIEW', max_length=16)),
                ('validation_status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('MANUAL_REVIEW', 'Manuel İnceleme')], db_index=True, default='MANUAL_REVIEW', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('APPROVED', 'Onaylı'), ('REJECTED', 'Reddedildi'), ('COMMITTED', 'Commit Edildi')], db_index=True, default='DRAFT', max_length=16)),
                ('display_title', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('validation_messages', models.JSONField(blank=True, default=list, help_text="[{'code': str, 'level': str, 'msg': str, 'field': ''}]")),
                ('created_object_app', models.CharField(blank=True, default='', max_length=64)),
                ('created_object_model', models.CharField(blank=True, default='', max_length=64)),
                ('created_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_records', to='imports.importbatch')),
            ],
            options={
                'verbose_name': 'Draft Kayıt',
                'verbose_name_plural': 'Draft Kayıtlar',
                'ordering': ['batch', 'source_row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportDraftField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('field_name', models.CharField(max_length=64)),
                ('raw_value', models.TextField(blank=True, default='')),
                ('normalized_value', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('MANUAL_REVIEW', 'Manuel İnceleme')], default='OK', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('draft_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_states', to='imports.importdraftrecord')),
            ],
            options={
                'verbose_name': 'Draft Alan Durumu',
                'ordering': ['draft_record', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('CRITICAL', 'Kritik')], default='INFO', max_length=16)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.importbatch')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('RAR', 'RAR'), ('ZIP', 'ZIP'), ('FOLDER', 'Klasör'), ('MANUAL', 'Manuel')], default='EXCEL', max_length=16)),
                ('target_module', models.CharField(choices=[('INVOICE', 'Fatura / Ödeme'), ('SUBSCRIPTION', 'Abonelik'), ('SITEX', 'SiteX'), ('PROPERTY_TAX', 'Emlak Vergisi'), ('GUARANTEE', 'Teminat'), ('OFFICIAL', 'Resmi Ödemeler'), ('INTEGRATOR', 'Entegratör'), ('MASTER', 'Master Tablolar'), ('GENERIC', 'Genel / Tanımsız')], default='GENERIC', max_length=24)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_profiles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapping Şablonu',
                'verbose_name_plural': 'Mapping Şablonları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratılma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Pasifleştirme')),
                ('archive_reason', models.TextField(blank=True, default='', verbose_name='Sebep')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('original_path', models.CharField(blank=True, default='', max_length=512)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=128)),
                ('file_role', models.CharField(blank=True, default='primary', max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='PARSED', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Pasifleştiren')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='imports.importbatch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_uses', to='documents.document')),
            ],
            options={
                'verbose_name': 'Import Kaynak Dosya',
                'verbose_name_plural': 'Import Kaynak Dosyalar',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.AddField(
            model_name='importdraftrecord',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_records', to='imports.importsourcefile'),
        ),
        migrations.AddIndex(
            model_name='importdraftrecord',
            index=models.Index(fields=['batch', 'validation_status'], name='imports_imp_batch_i_6c011f_idx'),
        ),
        migrations.AddIndex(
            model_name='importdraftrecord',
            index=models.Index(fields=['batch', 'status'], name='imports_imp_batch_i_3fa10b_idx'),
        ),
    ]
